version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: 'rabbitmq-test'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

